config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  resources :dogs do
    resources :bookings, only: [ :new, :create ]
  end
  resources :bookings, only: [:update, :show] do
    resources :reviews, only: [:new, :create]
  end
  devise_for :users
  get 'dashboard', to: 'pages#dashboard'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :dog
  has_one :review

  enum status: { pending: 0, accepted: 1, refused: 2, cancelled: 3 }
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/dog.rb
class Dog < ApplicationRecord
  belongs_to :user
  has_many_attached :photos
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  validates :address, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :dog
  belongs_to :user
  belongs_to :booking
end

app/models/user.rb
class User < ApplicationRecord
  has_many :dogs
  has_many :bookings
  has_many :reviews
  has_one_attached :photo
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, :authenticate_user!, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :gender, :age, :address, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :gender, :age, :address, :photo])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @dog = Dog.find(params[:dog_id])
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @dog = Dog.find(params[:dog_id])
    @booking.dog = @dog
    @booking.user = current_user
    if @booking.save!
      redirect_to booking_path(@booking)
    else
      render :new
    end
  end

  def update
    @booking = Booking.find(params[:id])
    if @booking.dog.user == current_user
      if params[:commit] == 'Accept'
        @booking.accepted!
      elsif params[:commit] == 'Cancel'
        @booking.cancelled!
      else
        @booking.refused!
      end
      @booking.save
    end
    if @booking.user == current_user && params[:commit] == 'Cancel'
      @booking.cancelled!
    end
    respond_to do |format|
      format.html { redirect_to dashboard_path }
      format.json { render json: success_data }
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :price, :status)
  end

  def success_data
    {
      inserted_item: render_to_string(partial: 'pages/pending-request.html', locals: { dog: @booking.dog }),
      history_item: render_to_string(partial: 'pages/request-history.html', locals: { dog: @booking.dog }),
      rental_item: render_to_string(partial: 'pages/rental-request.html')
    }
  end
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  def index
    if params.dig(:dog,:address)
      @dogs = Dog.near(params.dig(:dog,:address), 30)
      @markers = @dogs.geocoded.map do |dog|
        {
          lat: dog.latitude,
          lng: dog.longitude,
          infoWindow: render_to_string(partial: "info_window", locals: { dog: dog }),
        }
      end
    else
      @dogs = Dog.near("Paris france", 10)
      @markers = @dogs.geocoded.map do |dog|
        {
          lat: dog.latitude,
          lng: dog.longitude,
          infoWindow: render_to_string(partial: "info_window", locals: { dog: dog }),
        }
      end
    end
  end

  def show
    @dog = Dog.find(params[:id])
  end

  def new
    @dog = Dog.new(params[:id])
  end

  def create
    @dog = Dog.new(dog_params)
    @dog.user = current_user
      if @dog.save
        redirect_to dog_path(@dog)
      else
        render "pages/dashboard"
      end
  end

  def edit
    @dog = Dog.find(params[:id])
    if @dog.user != current_user
      redirect_to root_path
    end
  end

  def update
    @dog = Dog.find(params[:id])
    @dog.update(dog_params)
    if @dog.save!
      redirect_to dashboard_path
    else
      render :edit
    end
  end

  def destroy
    @dog = Dog.find(params[:id])
    @dog.destroy
    redirect_to dashboard_path
  end


  private

  def dog_params
    params.require(:dog).permit(:name, :age, :color, :size, :is_sterilized, :rating, :comments, :breed, :address, :description, photos: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end

  def dashboard

  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
    @booking = Booking.find(params[:booking_id])
  end

  def create
    @review = Review.new(review_params)
    @booking = Booking.find(params[:booking_id])
    @review.booking = @booking
    @review.dog = @booking.dog
    @review.user = @booking.user
    @review.save
    @dog = @booking.dog
    if @dog.reviews.count == 1
      @dog.rating = @dog.reviews.first.rating
    else
      ratings = Review.where("reviews.dog_id = ?", @dog.id).map { |review| review.rating }
      @dog.rating = ratings.sum.fdiv(ratings.count).round
    end
    @dog.save
    redirect_to dashboard_path
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div class="row mt-5">
  <div class="col-12 col-lg-6 offset-lg-3">
    <h1>Start your adventure with <%= @dog.name %> the dog</h1>
    <%= simple_form_for [ @dog, @booking ] do |f| %>
      <%= f.input :start_date, as: :string, required: false, input_html: {id: "range_start"} %>
      <%= f.input :end_date, as: :string, required: false, input_html: {id: "range_end"} %>
      <%= f.submit "Submit booking", class: "btn btn-success" %>
    <% end %>
  </div>
</div>

app/views/bookings/show.html.erb
<div style=container>
<head>
  <link href="https://fonts.googleapis.com/css?family=Fira+Sans+Condensed:300,400,600i&display=swap" rel="stylesheet">
</head>
<header> Thank you for your order! </header>
<div class="infocardContainer">
  <div id="main">
    <%= cl_image_tag @booking.dog.photos.first.key, height: 100, crop: :thumb %>
  </div>
  <div id="textbois">
    <h2><%= "#{@booking.dog.name}"%></h2>
    <h4><%="Start date: #{@booking.start_date}" %></h4>
    <h4><%= "End date #{@booking.end_date}" %></h4>
  </div>
</div>
</div>

<div class=button-show>
    <%= link_to "View your dashboard", dashboard_path, class: "btn btn-gradient" %>
    <%= link_to "Back to your dog", dog_path(@booking.dog), class: "btn btn-gradient" %>
  </div>
  </div>
<!-- </div>
<div class="booking-dog-card">
<%= "Book #{@booking.dog.name}" %>
<%= "Start date: #{@booking.start_date}" %>
<%= "End date #{@booking.end_date}" %>
<%= "Total Price: #{@booking.price}" %>
<%= "Dog owner's name: #{@booking.dog.user.first_name}"%>
</div> -->

app/views/dogs/_info_window.html.erb
<h2><%= dog.name %></h2>
<p><%= dog.address %></p>

app/views/dogs/create.html.erb
<h1>Dogs#create</h1>
<p>Find me in app/views/dogs/create.html.erb</p>

app/views/dogs/edit.html.erb
<div class="row mt-5">
  <div class="col-12 col-lg-6 offset-lg-3">
    <h2>Update your dog</h2>
    <%= simple_form_for(@dog) do |f| %>
      <%= f.input :name, label: "Prénom" %>
      <%= f.input :age, label: "Âge", min: 0 %>
      <%= f.input :address, label: "Adresse" %>
      <%= f.input :color, label: "Couleur" %>
      <%= f.input :breed, label: "Race" %>
      <%= f.input :description, label: "Description" %>
      <%= f.input :size, :as => :select,
                :collection => %w[Petite Moyenne Grande],
                :label => "Taille" %>
      <%= f.input :is_sterilized, :as => :select,
                :collection => [['Non',false],['Oui',true]],
                :include_blank => false,
                :label => "Stérélisé(e)" %>
      <%= f.input :photos, as: :file, input_html: { multiple: true } %>
      <%= f.submit %>
      <% end %>
    <div class="dog-photos mt-4">
      <% @dog.photos.each do |photo| %>
        <%= cl_image_tag photo.key, height: 200, width: 250, crop: :fill %>
      <% end %>
    </div>
  </div>
</div>

app/views/dogs/index.html.erb
<h1 class="text-center mt-3 font-weight-bold bg-light">Dogs in your area</h1>
<%= render 'shared/searchbar' %>
  <div class="row">
    <div class="col-8 cards-container">
      <% @dogs.each do |dog| %>
        <%= link_to dog_path(dog), class:"card-dog" do %>
            <%= cl_image_tag dog.photos.first.key%>
            <div class="card-dog-infos">
              <div>
                <h2><%= dog.name %></h2>
                <p><%= dog.description %></p>
              </div>
              <% unless dog.rating.nil? %>
                <p class="star-icons">
                  <%= "<i class='fas fa-star active'></i>".html_safe * dog.rating %>
                  <%= "<i class='fas fa-star'></i>".html_safe * (5 - dog.rating) %>
                </p>
              <% end %>
            </div>
        <% end %>
      <% end %>
    </div>
    <div id="map" class="col-4"
      style="width: 100%; height: 100vh;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
  </div>

app/views/dogs/new.html.erb
<h1>Dogs#new</h1>
<p>Find me in app/views/dogs/new.html.erb</p>

app/views/dogs/show.html.erb
<section>
  <div class="card-show-dog">
    <div class="card-show-image-dog">
    <% if @dog.photos.attached? %>
      <div class="carousel slide" id="main-carousel" data-ride="carousel">
        <ol class="carousel-indicators">
          <% i = 0 %>
          <% while i < @dog.photos.count %>
            <li data-target="#main-carousel" data-slide-to=<%"#{i}"%> <% if i.zero? %> class="active" <% end %> ></li>
            <% i += 1 %>
          <% end %>
        </ol><!-- /.carousel-indicators -->
        <div class="carousel-inner">
          <div id="carousel-show" class="carousel-item active">
            <%= cl_image_tag @dog.photos.first.key, :class => "w-100" %>
          </div>
          <% photo_num = @dog.photos.first.id + 1 %>
          <% while photo_num < @dog.photos.count + @dog.photos.first.id %>
            <div class="carousel-item">
              <%= cl_image_tag @dog.photos.find(photo_num).key, :class => "w-100" %>
            </div>
            <% photo_num += 1 %>
          <% end %>
        </div>
        <a href="#main-carousel" class="carousel-control-prev" data-slide="prev">
          <span class="carousel-control-prev-icon"></span>
          <span class="sr-only" aria-hidden="true">Prev</span>
        </a>
        <a href="#main-carousel" class="carousel-control-next" data-slide="next">
          <span class="carousel-control-next-icon"></span>
          <span class="sr-only" aria-hidden="true">Next</span>
        </a>
      </div>
      <% else %>
        <%= image_tag 'dog.jpg', :class => "w-100" %>
      <% end %>
    </div>
    <div class="card-show-dog-infos">
      <h1><%= @dog.name %></h1>
      <% unless @dog.rating.nil? %>
        <p class="star-icons">
          <%= "<i class='fas fa-star active'></i>".html_safe * @dog.rating %>
          <%= "<i class='fas fa-star'></i>".html_safe * (5 - @dog.rating) %>
        </p>
      <% end %>
      <p><%= "Race: #{@dog.breed}" %></p>
      <p><%= "Age: #{@dog.age}" %></p>
      <p><%= "Couleur #{@dog.color}" %></p>
      <p><%= "Taille: #{@dog.size}" %></p>
      <p><%= @dog.is_sterilized ? "#{@dog.name} est stérilisé(e)" : "#{@dog.name} n'est pas stérilisé(e)" %></p>
      <div class=btn-show-rent>
        <%= link_to "Rent #{@dog.name}", new_dog_booking_path(@dog), class: "btn btn-success rounded btn-lg btn-block mt-4" %>
      </div>
    </div>
  </div>

</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentYourDog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <link href='https://api.mapbox.com/mapbox-gl-js/v2.2.0/mapbox-gl.css' rel='stylesheet' />
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/pages/_pending-request.html.erb
<% pending_bookings = dog.bookings.where(status: 'pending').order('created_at desc') %>
<% if pending_bookings == [] %>
<div class="no-pending-message">
  <p>You don't have any pending requests for <%= dog.name %></p>
</div>
<% else %>
<div class="request-cards">
  <% pending_bookings.each do |booking| %>
  <div class="request-card">
    <div class="request-card-left">
    <% if booking.user.photo.attached? %>
      <%= cl_image_tag booking.user.photo.key, class: 'avatar dropdown-toggle', id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
    <% else %>
      <%= image_tag 'blank_avatar.png', class: 'avatar dropdown-toggle', id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
    <% end %>
    </div>
    <div class="request-card-right">
      <p>Request from <%= booking.user.first_name %> <%= booking.user.last_name %></p>
      <p> From <%= booking.start_date %> to <%= booking.end_date %> </p>
      <div class="request-card-buttons">
        <%= simple_form_for(booking, data: {
                      update_status_target: 'acceptForm',
                      action: 'submit->update-status#send'
                    }) do |f| %>
          <%= hidden_field_tag 'commit', 'Accept' %>
          <%= f.button :submit, 'Accept', class: 'btn btn-success' %>
        <% end %>
        <%= simple_form_for(booking, data: {
                      update_status_target: 'refuseForm',
                      action: 'submit->update-status#send'
                    }) do |f| %>
          <%= hidden_field_tag 'commit', 'Decline' %>
          <%= f.button :submit, 'Decline', class: 'btn btn-danger' %>
        <% end %>
      </div>
    </div>
  </div>
  <% end %>
</div>
<% end %>

app/views/pages/_rental-request.html.erb
<% current_user.bookings.order('created_at desc').each do |booking| %>
<div class="my-rental-request">

  <% dog = booking.dog %>
  <% if !dog.photos.empty? %>
  <div class="my-rental-request-img" style="background-image: url('<%= cl_image_path dog.photos.first.key, height: 100, crop: :thumb %>');">
  <% else %>
  <div class="my-rental-request-img" style="background-image: url('<%= image_path "dog.jpg" %>');">
  <% end %>
  </div>
  <div class="my-rental-request-right">
    <div class="my-rental-request-infos">
      <div class="my-rental-request-infos-dog">
        <p><span><%= dog.name %></span> - <%= dog.age %> ans (<%= dog.breed %>) </p>
        <p><em><%= dog.color %> / <%= dog.size %></em></p>
      </div>
      <div class="my-rental-request-infos-dog-owner">
        <p>Dog owner: <%= dog.user.first_name %> <%= dog.user.last_name %></p>
        <% if dog.user.photo.attached? %>
        <%= cl_image_tag dog.user.photo.key, class: 'avatar dropdown-toggle', id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% else %>
        <%= image_tag 'blank_avatar.png', class: 'avatar dropdown-toggle', id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% end %>
      </div>
    </div>
    <div class="my-rental-request-dates">
      <p> From <%= booking.start_date %> to <%= booking.end_date %> </p>
    </div>
    <div class="my-rental-request-status">
      <% if DateTime.now - booking.end_date > 0 && booking.review.nil? %>
        <%= link_to new_booking_review_path(booking) do %>
          <div class="leave-a-review">
            <p>Did your enjoy your time with <%= dog.name %> ? Leave a review !</p>
          </div>
        <% end %>
      <% elsif DateTime.now - booking.end_date > 0 %>
        <div class="left-review">
          <p>Thanks for the review your left for <%= dog.name %>!</p>
        </div>
      <% else %>
        <div class="rental-request-message">
        <% case booking.status %>
        <% when "pending" %>
          <p class='pending-message'><%= dog.user.first_name %> did not respond to your request yet</p>
          <%= simple_form_for(booking, data: {
                        update_status_target: 'cancelForm',
                        action: 'submit->update-status#send'
                      }) do |f| %>
            <%= hidden_field_tag 'commit', 'Cancel' %>
            <%= f.button :submit, 'Cancel', class: 'btn btn-warning' %>
          <% end %>
        <% when "accepted" %>
          <p class='accepted-message'><%= dog.user.first_name %> accepted your request</p>
        <% when "refused" %>
          <p class='refused-message'><%= dog.user.first_name %> refused your request</p>
        <% when "cancelled" %>
          <p class='refused-message'>You canceled your request</p>
        <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<% end %>

app/views/pages/_request-history.html.erb
<% all_bookings = dog.bookings.where.not(status: 'pending').order('created_at desc') %>
<% if all_bookings == [] %>
<div class="no-pending-message">
  <p>Your requests history for <%= dog.name %> is empty.</p>
</div>
<% else %>
<div class="request-cards">
  <% all_bookings.each do |booking| %>
  <div class="request-card">
    <div class="request-card-left">
    <% if booking.user.photo.attached? %>
      <%= cl_image_tag booking.user.photo.key, class: 'avatar dropdown-toggle', id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
    <% else %>
      <%= image_tag 'blank_avatar.png', class: 'avatar dropdown-toggle', id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
    <% end %>
    </div>
    <div class="request-card-right">
      <p>Request from <%= booking.user.first_name %> <%= booking.user.last_name %></p>
      <p> From <%= booking.start_date %> to <%= booking.end_date %> </p>
      <div class="request-card-buttons">
        <% case booking.status %>
        <% when 'accepted' %>
        <p class='accepted-message'>You accepted this request</p>
        <% when 'refused' %>
        <p class='refused-message'>You refused this request</p>
        <% when 'cancelled' %>
        <p class='refused-message'><%= booking.user.first_name %> cancelled this request</p>
        <% end %>
      </div>
    </div>
  </div>
  <% end %>
</div>
<% end %>

app/views/pages/dashboard.html.erb
<div class="container">
  <h2 class="dashboard-header">Dashboard</h2>

  <ul class="tabs list-inline" id="mytabs">
    <li class="tab list-inline-item active" id="my-dogs">My dogs</li>
    <li class="tab list-inline-item" id="add-a-dog">Add a dog</li>
    <li class="tab list-inline-item" id="my-rental-requests">My rental requests</li>
    <li class="tab list-inline-item" id="my-informations">My informations</li>
  </ul>

  <div data-controller="update-status">
    <div class="my-dogs">
      <% current_user.dogs.each do |dog| %>
      <h3><%= dog.name %></h3>
      <div class="my-dogs-grid">
        <div class="my-dogs-card">
          <% if !dog.photos.empty? %>
          <div class="my-dogs-card-img" style="background-image: url('<%= cl_image_path dog.photos.first.key, height: 100, crop: :thumb %>');">
          <% else %>
          <div class="my-dogs-card-img" style="background-image: url('<%= image_path "dog.jpg" %>');">
          <% end %>
          </div>
          <div class="my-dogs-card-infos">
            <div class="my-dogs-card-text">
              <p><span><%= dog.name %></span> - <%= dog.age %> ans (<%= dog.breed %>) </p>
                <% unless dog.rating.nil? %>
                  <p class="star-icons">
                    <%= "<i class='fas fa-star active'></i>".html_safe * dog.rating %>
                    <%= "<i class='fas fa-star'></i>".html_safe * (5 - dog.rating) %>
                  </p>
                <% end %>
            </div>
            <p><em><%= dog.color %> / <%= dog.size %></em></p>
            <div class="my-dogs-card-buttons">
            <%= link_to 'See', dog_path(dog), class: 'btn btn-primary' %>
            <%= link_to 'Edit', edit_dog_path(dog), class: 'btn btn-info' %>
            <%= link_to 'Delete', dog_path(dog), method: :delete, data: { confirm: 'Are you sure you want to delete this dog ?'}, class: 'btn btn-danger' %>
            </div>
          </div>
        </div>

        <div class="my-dogs-requests">
          <h4>Pending Requests</h4>
          <div class="pending-requests" data-update-status-target='accept'>
            <%= render 'pending-request', dog: dog %>
          </div>
        </div>
      </div>

      <div class="request-history-cards">
        <h4>Requests history for <%= dog.name %></h4>
        <div class="request-history" data-update-status-target='history'>
          <%= render 'request-history', dog: dog %>
        </div>
      </div>
      <hr>
    <% end %>
    </div>

    <div class="my-rental-requests">
      <div class="rental-requests" data-update-status-target="rental">
        <%= render 'rental-request' %>
      </div>
    </div>
  </div>


  <div class="add-a-dog mb-5">
    <div class="row">
      <div class="col-12 col-lg-6 offset-lg-3">
        <h3 class="text-center">Add a dog</h3>
        <% @dog = Dog.new(user_id: current_user.id) %>
        <%= simple_form_for(@dog) do |f| %>
          <%= f.input :name, :label => "Prénom" %>
          <%= f.input :age, :label => "Age", min: 0 %>
          <%= f.label "Adresse"%>
          <%= f.text_field :address, :class => "search-input", required: true%>
          <%= f.input :color, label: "Couleur" %>
          <%= f.input :breed, :label => "Race" %>
          <%= f.input :description, :label => "Description" %>
          <%= f.input :size, :as => :select,
                    :collection => %w[Petite Moyenne Grande],
                    :label => "Taille" %>
          <%= f.input :is_sterilized, :as => :select,
                    :collection => [['Non',false],['Oui',true]],
                    :include_blank => false,
                    :label => "Stérélisé(e)" %>
          <%= f.input :photos, as: :file, input_html: { multiple: true } %>
          <% @dog.photos.each do |photo| %>
            <%= cl_image_tag photo.key, height: 200, width: 250, crop: :fill %>
          <% end %>
          <%= f.submit%>
        <% end %>
      </div>
    </div>
  </div>

  <div class="my-informations">
    <div class="row">
      <div class="info-dash col-12 col-lg-6 offset-lg-3">
        <h6>First Name</h6>
        <p><%= current_user.first_name %></p>
        <h6>Last Name</h6>
        <p><%= current_user.last_name %></p>
        <h6>Email address</h6>
        <p><%= current_user.email %></p>
        <h6>Age</h6>
        <p><%= current_user.age %></p>
        <h6>Address</h6>
        <p><%= current_user.address %></p>
        <h6>Gender</h6>
        <p><%= current_user.gender %></p>
        <%= link_to "Edit your profile", "/users/edit", class: 'btn btn-info btn-block' %>
      </div>
    </div>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="row">
  <div class="col-12 col-lg-6 offset-lg-3">
    <div class="review-form" id="stars-form">
      <h2>Leave a review for <%= @booking.dog.name %></h2>
      <%= simple_form_for [@booking, @review] do |f| %>
        <%= f.input :content %>
        <%= f.input :rating, as: :radio_buttons, collection: (1..5).to_a.map { |n| [n, "<i class='fas fa-star'></i>".html_safe] }, value_method: :first, label_method: :second, input_html: { style: "display: none" } %>
        <%= f.submit %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div id="navbar_top" class="navbar navbar-expand-sm navbar-light navbar-rent-your-dog">
  <%= link_to "/", class: "navbar-brand", id: "home-page" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'All dogs', dogs_path, class: "text-dark" %>
      </li>
      <li class="nav-item">
        <%= link_to 'My dashboard', dashboard_path, class: "text-dark" %>
      </li>
      <% if user_signed_in? %>
      <li class="nav-item">
        <%= "Hello #{current_user.first_name}" %>
      </li>
      <li class="nav-item dropdown">
        <% if current_user.photo.attached? %>
        <%= cl_image_tag current_user.photo.key, class: 'avatar dropdown-toggle', id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% else %>
        <%= image_tag 'blank_avatar.png', class: 'avatar dropdown-toggle', id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% end %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to 'Log out', destroy_user_session_path, class: "dropdown-item", method: :delete %>
        </div>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to 'Log in', new_user_session_path%>
      </li>
      <li class="nav-item">
        <%= link_to 'Sign up', new_user_registration_path%>
      </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_searchbar.html.erb
<div class="container">
  <%= form_for( :dog, :html => { class: "product-search d-flex justify-content-center" }, url:dogs_path, method: :get) do |f| %>
    <div class="search-element">
      <%= f.text_field :address, :placeholder => "What is your address ?", :class => "search-input", required: true %>
      <%= f.submit "Look for a dog", :class => "search-button"%>
    </div>
  <% end %>
</div>